### ISSUE TITLE
--net=host causes loop?

### ISSUE THREAD

**Issue by JoeOrtiz** [gliderlabs/resolvable#15]
I have many services under --net=host, but this appears in the logs continuously:

2015/12/07 20:18:10 error adding container a3fac3a90373: IP not available with network mode "host"
2015/12/07 20:18:11 error adding container a3fac3a90373: IP not available with network mode "host"
2015/12/07 20:18:13 error adding container ea440bf54b63: IP not available with network mode "host"
2015/12/07 20:18:13 error adding container ea440bf54b63: IP not available with network mode "host"
2015/12/07 20:18:15 error adding container 8d302b8d7e89: IP not available with network mode "host"
2015/12/07 20:18:15 error adding container 8d302b8d7e89: IP not available with network mode "host"
2015/12/07 20:18:20 error adding container c93085880387: IP not available with network mode "host"

Anyway for it just to ignore those ? So it can take less resources?

**Comment by ekristen** [comment]
that is just a warning that can be ignored. they should only appear upon restart, or when a container is started/restarted that is in net host mode, there is not loop AFAIK.

**Comment by MichaelMackus** [comment]
What about containers that are run within a custom docker network? Even if I start resolvable within that network (with `--net=NETWORK`) I get errors similar to above (`error adding container 67c695bea6b0: unknown network mode%!(EXTRA string=NETWORK)`) and I'm unable to ping/access containers via their hostname/name.docker as before.

**Comment by ekristen** [comment]
Unfortunately there are several short comings i've found with resolvable, I'm sure they will get resolved in time. It doesn't support networks unfortunately.

**Comment by MichaelMackus** [comment]
I assumed as much. Thanks for the input. I'll probably just end up using a single proxy via nginx or similar in the meantime. At least that way I still get networks and can use a single IP address for all hosts.

**Comment by tilgovi** [comment]
This issue can be closed, and if there's specific work needed to play more nicely with docker networking that should be new, specific issues.
